config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views


from mainapp.views import DataPreview, LoadUserLikes

from django.views.decorators.cache import cache_page
from action.api import UserDataDetail, UserDataList


urlpatterns = [
    url(
        r'^$',
        view=TemplateView.as_view(template_name='landing.html'),
        name='home'
    ),
    url(
        r'^load/',
        view=LoadUserLikes.as_view(),
        name='load'
    ),
    # url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('fbstats.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(
        r'^api-auth/', include(
            'rest_framework.urls', namespace='rest_framework')),
    url(
        r'^preview/$',
        view=DataPreview.as_view(),
        name='data-preview'
    )
    # Your stuff: custom urls includes go here


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

fbstats/users/urls.py
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views


urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

action/models.py
from __future__ import unicode_literals

from django.db import models
from fbstats.users.models import User
from django.contrib.postgres.fields import JSONField
# Create your models here.


class UserData(models.Model):
    user = models.ForeignKey(User)

    ver_code = models.TextField(null=True, blank=True)
    mobile_ver_flg = models.BooleanField(default=False)
    email_ver_flg = models.BooleanField(default=False)

    pre_charity_org = models.IntegerField(default=0)

    ad_view_total = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    created_by = models.TextField(null=True, blank=True)
    last_upd = models.DateTimeField(auto_now_add=True)
    last_upd_by = models.TextField(null=True, blank=True)

    likes = JSONField(null=True, blank=True)

    def __str__(self):
        return str(self.user.first_name) + " " + str(self.user.last_name)

fbstats/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

mainapp/models.py
from django.db import models


class FacebookPost(models.Model):
    page_id = models.CharField(max_length=255, unique=True)
    posts = models.TextField(null=True, blank=True)
    page_info = models.TextField(null=True, blank=True)
    most_liked_post = models.TextField(null=True, blank=True)

    def __str__(self):
        return str(self.page_id)

action/views.py
# from django.contrib.auth.mixins import LoginRequiredMixin
# from django.shortcuts import render, get_object_or_404

fbstats/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

mainapp/views.py
# -*- coding: utf-8 -*-
import json
from django.views.generic import View
from rest_framework.views import APIView
from rest_framework.response import Response
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
import facebook
from allauth.socialaccount.models import SocialToken, SocialApp
from action.models import UserData
from .pull_likes import get_myfacebook_likes
import requests
import sys


class DataPreview(LoginRequiredMixin, View):
    """Module for previewing data from facebook."""
    template_name = 'preview.html'

    def get_context_data(self, **kwargs):
        context = {}
        tokens = SocialToken.objects.filter(
            account__user=self.request.user,
            account__provider='facebook'
        )
        if tokens:
            context['token'] = tokens[0].token

        fb_app = get_object_or_404(SocialApp, id=1)
        context['app_id'] = fb_app.client_id
        return context

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.get_context_data())


class LoadUserLikes(LoginRequiredMixin, View):
    """Module for previewing data from facebook."""
    template_name = 'load.html'

    def get_context_data(self, **kwargs):
        context = {}
        tokens = SocialToken.objects.filter(
            account__user=self.request.user,
            account__provider='facebook'
        )
        if tokens:
            context['token'] = tokens[0].token

        fb_app = get_object_or_404(SocialApp, id=1)
        context['app_id'] = fb_app.client_id
        return context

    def get(self, request, *args, **kwargs):
        tokens = SocialToken.objects.filter(
            account__user=request.user,
            account__provider='facebook'
        )

        user_data = UserData.objects.get_or_create(user=request.user)

        myfbgraph = facebook.GraphAPI(tokens[0].token)
        my_likes = get_myfacebook_likes(myfbgraph)
        user_data[0].likes = my_likes
        user_data[0].save()

        return render(request, self.template_name, self.get_context_data())

fbstats/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

fbstats/templates/base.html
{% load staticfiles i18n %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock title %} | Facebook Stats</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/stylish-portfolio.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/5.0.0/bootstrap-social.css">
    <!-- Custom Fonts -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
    {% block css %} {% endblock %}
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <a id="menu-toggle" href="#" class="btn btn-dark btn-lg toggle"><i class="fa fa-bars"></i></a>
    <nav id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <a id="menu-close" href="#" class="btn btn-light btn-lg pull-right toggle"><i class="fa fa-times"></i></a>

            {% if request.user.is_authenticated %}
            <li class="sidebar-brand">
                <a href="#" id="close">Welcome {{request.user.first_name}}</a>
            </li>
            <li>
                <a href="/accounts/social/connections/">Account Connections</a>
            </li>
            <li>
                <a href="/accounts/logout/">Logout</a>
            </li>
            {% else %}
            <li class="sidebar-brand">
                <a href="#" id="close">Facebook Stats</a>
            </li>
            <li>
                <a href="/accounts/facebook/login/?method=oauth2">Login</a>
            </li>
            {% endif %}
        </ul>
    </nav>


    {% block content %}
    {% endblock content %}


    <!-- jQuery -->
    <script src="{% static 'js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <!-- Custom Theme JavaScript -->
    <script>
    // Closes the sidebar menu
    $("#menu-close, #close").click(function(e) {
        e.preventDefault();
        $("#sidebar-wrapper").toggleClass("active");
    });
    // Opens the sidebar menu
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#sidebar-wrapper").toggleClass("active");
    });
    </script>
    {% block javascript %}
    {% endblock javascript %}
</body>

</html>

fbstats/templates/bootstrap4/field.html
{% load crispy_forms_field %}

{% if field.is_hidden %}
    {{ field }}
{% else %}
    {% if field|is_checkbox %}
        <div class="form-group{% if using_grid_layout %} row{% endif %}">
        {% if label_class %}
            <div class="controls col-{{ bootstrap_device_type }}-offset-{{ label_size }} {{ field_class }}">
        {% endif %}
    {% endif %}
    <{% if tag %}{{ tag }}{% else %}div{% endif %} id="div_{{ field.auto_id }}" {% if not field|is_checkbox %}class="form-group{% if using_grid_layout %} row{% endif %}{% else %}class="checkbox{% endif %}{% if wrapper_class %} {{ wrapper_class }}{% endif %}{% if form_show_errors%}{% if field.errors %} has-danger{% endif %}{% endif %}{% if field.css_classes %} {{ field.css_classes }}{% endif %}">
        {% if field.label and not field|is_checkbox and form_show_labels %}
            <label for="{{ field.id_for_label }}" class="form-control-label {{ label_class }}{% if field.field.required %} requiredField{% endif %}">
                {{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
            </label>
        {% endif %}

        {% if field|is_checkboxselectmultiple %}
            {% include 'bootstrap4/layout/checkboxselectmultiple.html' %}
        {% endif %}

        {% if field|is_radioselect %}
            {% include 'bootstrap4/layout/radioselect.html' %}
        {% endif %}

        {% if not field|is_checkboxselectmultiple and not field|is_radioselect %}
            {% if field|is_checkbox and form_show_labels %}
                <label for="{{ field.id_for_label }}" class="{% if field.field.required %} requiredField{% endif %}">
                    {% crispy_field field %}
                    {{ field.label|safe }}
                    {% include 'bootstrap4/layout/help_text_and_errors.html' %}
                </label>
            {% else %}
                <div class="{{ field_class }}">
                    {% crispy_field field %}
                </div>
                {% include 'bootstrap4/layout/help_text_and_errors.html' %}
            {% endif %}
        {% endif %}
    </{% if tag %}{{ tag }}{% else %}div{% endif %}>
    {% if field|is_checkbox %}
        {% if label_class %}
            </div>
        {% endif %}
        </div>
    {% endif %}
{% endif %}

fbstats/templates/bootstrap4/layout/field_errors_block.html
{% if form_show_errors and field.errors %}
    {% for error in field.errors %}
        <p id="error_{{ forloop.counter }}_{{ field.auto_id }}" class="text-danger help-block">{{ error }}</p>
    {% endfor %}
{% endif %}

fbstats/templates/create.html
{% extends "base.html" %}
{% load staticfiles i18n %}

{% block title %}Create UserData{% endblock title %}

{% block css %}
<style type="text/css">
</style>
{% endblock css %}

{% block content %}
    <div class="container" style="margin-top: 100px;">
      <div class="row">
        <div class="col-md-12">
            <div class="alert alert-success" role="alert" style="display: none" id="success-msg"></div>
            <h1>Create User-Data</h1>
            <form>
              <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control" name="name" id="name" placeholder="Name">
              </div>
              <div class="form-group">
                <label for="text">Text</label>
                <textarea class="form-control" id="text" name="text" placeholder="Text"></textarea>
              </div>
              <a href="#" class="btn btn-default" onclick="create_userdata()">Create</a>
            </form>
        </div>
      </div>
    </div>
{% endblock content %}

{% block javascript %}
<script src="{% static 'js/csrftoken.js' %}"></script>
<script type="text/javascript">
userid = "{{request.user.id}}";
form_data = {};
function create_userdata() {
  // body...
  var name = $('#name').val();
  var text = $('#text').val();
  form_data.name = name;
  form_data.text = text;
  form_data.user = parseInt(userid);
  console.log(form_data);
  var url = '/api/user-data/';
  $.post(url, form_data)
  .done(post_data_success(form_data));
}

function post_data_success(data) {
  // body...
  console.log("Success");
  console.log(data);
  $('#success-msg').text('User Data created successfully.');
  $('#success-msg').prop("style", "");
}
</script>
{% endblock javascript %}

fbstats/templates/landing.html
{% extends "base.html" %}
{% load staticfiles i18n %}

{% block title %}Home{% endblock title %}

{% block content %}
    <!-- Header -->
    <header id="top" class="header">
        <div class="text-vertical-center">
            <h1>Facebook Stats</h1>
            <h3>Trying to analyze some simple stats from Facebook API.</h3>
            <br>
            {% if request.user.is_authenticated %}
            <h2>Welcome {{request.user.get_full_name}} !</h2>
            <a href="{% url 'data-preview' %}" class="btn btn-dark btn-lg">Lets Start</a>
            {% else %}
             <a class="btn btn-social btn-facebook" href="/accounts/facebook/login/?method=oauth2">
                <span class="fa fa-facebook"></span> Sign in with Facebook
              </a>

              <!-- <a class="btn btn-social btn-twitter" href="/accounts/twitter/login/?method=oauth2">
                <span class="fa fa-twitter"></span> Sign in with Twitter
              </a> -->
            {% endif %}
        </div>
    </header>
{% endblock content %}

fbstats/templates/load.html
{% extends "base.html" %}
{% load staticfiles i18n %}

{% block title %}Welcome{% endblock title %}

{% block content %}
    <!-- Header -->
    <header id="top" class="header">
        <div class="text-vertical-center">
            <h1>Facebook Stats</h1>
            <h3>Trying to analyze some simple stats from Facebook API.</h3>
            <br>
            {% if request.user.is_authenticated %}
            <h2>Welcome {{request.user.get_full_name}} !</h2>
            <a href="{% url 'data-preview' %}" class="btn btn-dark btn-lg">Lets Start</a>
            {% else %}
             <a class="btn btn-social btn-facebook" href="/accounts/facebook/login/?method=oauth2">
                <span class="fa fa-facebook"></span> Sign in with Facebook
              </a>

              <!-- <a class="btn btn-social btn-twitter" href="/accounts/twitter/login/?method=oauth2">
                <span class="fa fa-twitter"></span> Sign in with Twitter
              </a> -->
            {% endif %}
        </div>
    </header>
{% endblock content %}

fbstats/templates/pages/about.html
{% extends "base.html" %}

fbstats/templates/pages/home.html
{% extends "base.html" %}

fbstats/templates/preview.html
{% extends "base.html" %}
{% load cache %}
{% load staticfiles i18n %}

{% block title %}Preview{% endblock title %}

{% block css %}
<style type="text/css">
  #most-liked-post, #second-most-liked-post{
    background-color: rgb(255, 255, 255);
    height: auto;
    padding-top: 20px;
    padding-bottom: 20px;
    border-radius: 5px;
  }
</style>
{% endblock css %}

{% cache 1200 content %}
{% block content %}
    <!-- Header -->
    {% now "jS F Y H:i" %}
    <header id="top" class="header">
        <div class="text-vertical-center">
            <h1><a href="/">Facebook Stats</a></h1>
            <h3>Trying to analyze some simple stats from Facebook API.</h3>
            <br>

            <div class="row">
              <div class="col-md-4 col-md-offset-1">
                <h2>Most Liked Post for this page !</h2>
                <div id="most-liked-post">
                </div>
                
              </div>
              <div class="col-md-4 col-md-offset-1">
                <h2>Second most liked post !</h2>
                  <div id="second-most-liked-post">
                  </div>
                  
              </div>
            </div>


        </div>
    </header>
{% endblock content %}
{% endcache %}

{% block javascript %}
<script src="{% static 'js/csrftoken.js' %}"></script>
<script type="text/javascript">
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '{{app_id}}',
      xfbml      : true,
      version    : 'v2.7'
    });
     $(document).trigger('fbload');
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));


$(document).on(
    'fbload',  //  <---- HERE'S OUR CUSTOM EVENT BEING LISTENED FOR
    function(){
        //some code that requires the FB object
        //such as...
        // FB.getLoginStatus(function(res){
        //     if( res.status == "connected" ){
        //         FB.api('/me', function(fbUser) {
        //             console.log("Open the pod bay doors, " + fbUser.name + ".");
        //         });
        //     }else{
        //         console.log('not logged in');
        //     }
        // });
        get_page_info();
        get_page_posts();
    }
);

function get_page_posts(){
    /* make the API call */
    FB.api(
        "/209242849219109/posts/?fields=story,created_time,message,link&access_token={{token}}",
        function (response) {
          if (response && !response.error) {
            // console.log('total posts' + response.data.length.toString());
            process_posts(response);
          }
        }
    );

}

function get_page_info(){
    /* make the API call */
    page_info = {};
    FB.api(
        "/209242849219109/?fields=about,affiliation,bio,category,cover,engagement,fan_count,is_verified,link&access_token={{token}}",
        function (response) {
          if (response && !response.error) {
            /* handle the result */
            // console.log(response);
            page_info = response;
          }
        }
    );
}

function post_data(data) {
  var url = "/api/stats/";
  $.ajax({
    type: "POST",
    url: url,
    data: JSON.stringify(data),
    dataType: 'json',
    contentType: "application/json",
    success: function(response){
      get_most_liked_post();
      var second_post_url = response.link;
      var second_post_html = '<div class="fb-post"'+ 
                      'data-href="' + second_post_url + '"' +
                      'data-width="500"></div>';
      $('#second-most-liked-post').html(second_post_html);
      FB.XFBML.parse(document.getElementById('second-most-liked-post'));
    },
    error: function( xhr, status, errorThrown ) {
      alert(errorThrown);
      }
  });
}

function get_most_liked_post(){
  var url = "/api/stats/?page_id=209242849219109";
   $.ajax({
    type: "GET",
    url: url,
    success: function(response){
      console.log('Most liked post');
      console.log(response);
      if(response.link.startsWith("https://www.facebook.com")){
        var post_url = response.link;
      }else{
        var post_url = "https://www.facebook.com/209242849219109/posts/" + response.id + "/"
      }
      console.log(post_url);
      var post_html = '<div class="fb-post"'+ 
                      'data-href="' + post_url + '"' +
                      'data-width="500"></div>';
      $('#most-liked-post').html(post_html);
      FB.XFBML.parse(document.getElementById('most-liked-post'));
    },
    error: function( xhr, status, errorThrown ) {
      alert(errorThrown);
      }
  });
}

function process_posts(posts) {
  aggregated_posts = [];
  for(i=0;i<posts.data.length;i++){
    var post = posts.data[i];
    var post_response = get_post_likes(post, posts.data.length);
  }
}

function get_post_likes(post, posts_len) {
  var url = "/" + post.id + "/likes/?summary=true"
  FB.api(
      url + "&access_token={{token}}",
      function (response) {
        if (response && !response.error) {
          post.total_likes = response.summary.total_count;
          aggregated_posts.push(post);
          if(aggregated_posts.length == posts_len){
              var processed_data = {
                posts: aggregated_posts,
                page_info: page_info
              }
              console.log(processed_data);
              post_data(processed_data);
          }
        }
      }
  );
}

</script>
{% endblock javascript %}

fbstats/templates/update.html
{% extends "base.html" %}
{% load staticfiles i18n %}

{% block title %}Update UserData{% endblock title %}

{% block css %}
<style type="text/css">
</style>
{% endblock css %}

{% block content %}
    <div class="container" style="margin-top: 100px;">
      <div class="row">
      <div class="col-md-12">
            <div class="alert alert-success" role="alert" style="visibility: hidden;" id="success-msg"></div>
      </div>
        <div class="col-md-6">
            <h1>Update User-Data</h1>

            <div class="list-group" id="user-data-list">
              <a href="#" class="list-group-item active">
                  List of User Data
              </a>
            </div>
        </div>
        <div class="col-md-6">
            <form style="margin-top: 50px; display: none;" id="updateform">
              <div class="form-group">
                <label for="id">User Data Id</label>
                <input type="text" class="form-control" name="id" id="id" placeholder="User Data Id" readonly="True">
              </div>
              <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control" name="name" id="name" placeholder="Name">
              </div>
              <div class="form-group">
                <label for="text">Text</label>
                <textarea class="form-control" id="text" name="text" placeholder="Text"></textarea>
              </div>
              <div class="form-group">
                <label for="user">User Id</label>
                <input type="text" class="form-control" id="user" name="user" placeholder="User" readonly="True">
              </div>
              
              <a href="#" class="btn btn-default" onclick="update_userdata()">Update</a>
            </form>
        </div>
      </div>
    </div>
{% endblock content %}

{% block javascript %}
<script src="{% static 'js/csrftoken.js' %}"></script>
<script type="text/javascript">
userid = "{{request.user.id}}";
form_data = {};
all_user_data = [];
$(document).ready(function() {
  get_all_userdata();
});

function get_all_userdata() {
  // body...
  var url = "/api/user-data/";
  $.get(
      url,
      function(data, status){
        all_user_data = data;
        for(var i=0;i<data.length;i++){
          var each_data = data[i];
          // var args = "'" + each_data.id + "', '" + each_data.name + "', '" + each_data.text + "', '" + each_data.id + "'";
          var args = "'" + i + "'";
          var content = "UserData ID: " + each_data.id + " Name: " + each_data.name + " Text: " + each_data.text + " User Id: " + each_data.user;
          var msg = '<a id="'+ each_data.id +'" href="#" class="list-group-item" onclick="set_userdata(' + args + ')">' + content + '</a>';
          $('#user-data-list').append(msg);
        }
  });
}

function update_userdata() {
  var name = $('#name').val();
  var text = $('#text').val();
  var userid = $("#user").val();
  var userdataid = $('#id').val();

  // update the global data
  for(var i=0;i<all_user_data.length;i++){
    if(userdataid == all_user_data[i].id){
      all_user_data[i].name = name;
      all_user_data[i].text = text;
      break;
    }
  }

  // update the a href text
  var content = "UserData ID: " + userdataid + " Name: " + name + " Text: " + text + " User Id: " + userid;
  $('#' + userdataid).text(content);

  form_data.name = name;
  form_data.text = text;
  form_data.user = parseInt(userid);

  var url = '/api/user-data/' + userdataid + "/";

  $.ajax({
    url: url,
    type: 'PUT',
    data: form_data,
    success: post_data_success(form_data)
  });

}

function set_userdata(index) {
  // hide the success msg
  $('#success-msg').prop("style", "visibility: hidden;");

  var udata = all_user_data[index];
  $('#id').val(udata.id);
  $('#name').val(udata.name);
  $('#text').val(udata.text);
  $('#user').val(udata.user);
  $('#updateform').prop('style', "margin-top: 50px;");
}

function post_data_success(data) {
  // body...
  $('#success-msg').text('User Data updated successfully.');
  $('#success-msg').prop("style", "");
}
</script>
{% endblock javascript %}

fbstats/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

fbstats/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

fbstats/templates/users/user_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Users</h2>

  <div class="list-group">
    {% for user in user_list %}
      <a href="{% url 'users:detail' user.username %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ user.username }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}